swab

diff --git a/virtualisation/qemu b/virtualisation/qemu
--- a/virtualisation/qemu
+++ b/virtualisation/qemu
@@ -1,18 +1,16 @@
 #!/run/current-system/sw/bin/bash
-
-
 GUEST_NAME="$1"
 HOOK_NAME="$2"
 STATE_NAME="$3"
 MISC="${@:4}"
 
-BASEDIR="$(dirname $0)"
+set -e  # Exit if any command fails
 
-SCRIPT="$BASEDIR/vms/$GUEST_NAME/$HOOK_NAME/$STATE_NAME.sh"
-
-set -e # If a script exits with an error, we should as well.
-
-if [ -e "$SCRIPT" ]; then
-    # If the script exists, execute it using eval
-    eval \"$SCRIPT\" "$@"
+# Special case for win11
+if [ "$GUEST_NAME" = "win11" ]; then
+    if [ "$HOOK_NAME" = "prepare" ] && [ "$STATE_NAME" = "begin" ]; then
+        nvidia-bind-vfio
+    elif [ "$HOOK_NAME" = "release" ] && [ "$STATE_NAME" = "end" ]; then
+        nvidia-unbind-vfio
+    fi
 fi
